<?php
/**
 * Created by PhpStorm.
 * User: Amr Saidam
 * Date: 9/18/2016
 * Time: 1:29 AM
 */

namespace App\Http\Controllers;
use Amp\Thread\Thread;


class ThreadTest extends Thread
{

//
//    public function start($options = 0)
//    {
//        parent::start($options); // TODO: Change the autogenerated stub
//
//
//        for ($i = 0; $i <= 100; $i++) {
//            echo '<br/>'.$i;
//        }
//
//    }


    public function run()
    {
//        parent::run(); // TODO: Change the autogenerated stub

        for ($i = 0; $i <= 100; $i++) {
            echo '<br/>' . $i;
        }
    }
}